apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: ludo
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
        - name: identity
          image: ghcr.io/ashwinkrishnaa29/ludo-identity:latest
          ports:
            - containerPort: 4001
          envFrom:
            - configMapRef:
                name: ludo-config
            - secretRef:
                name: ludo-secrets
          readinessProbe:
            httpGet:
              path: /readyz
              port: 4001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4001
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: "50m"
              memory: "96Mi"
            limits:
              cpu: "200m"
              memory: "192Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: identity
  namespace: ludo
spec:
  selector:
    app: identity
  ports:
    - port: 4001
      targetPort: 4001
